[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_22_0 = "jGq9BAvKeQswSH2jwSRxFN3XRt8TSZ5RcZYsByGeFRp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/aryan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
